[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "CLM5EU3_Ecosystem_Processes"
version = "0.0.1"
dependencies = [
    "requests",
    'importlib-metadata; python_version>"3.8"',
]

[tool.setuptools.packages]
find = {}

